package PokemonDemo;

import java.awt.image.BufferedImage;
import java.io.IOException;

import javax.imageio.ImageIO;

public class TImg {

	public static final int
	PLAYER = 0,
	F_PINK_SKIRT_WHITE_HAT = 1,
	M_BOY_BLUE_HAT=2,
	F_SCHOOLGIRL=3,
	M_BOY_SCOUT=4,
	F_GIRL_SCOUT=5,
	M_BUG_CATCHER=6,
	F_DITZY_HIPSTER=7,
	F_LITTLE_GIRLS=8,
	M_HIKER=9,
	F_KICKBOXER=10,
	M_FISHERMAN=11,
	M_BIKER_RED_HAT=12,
	F_BIKER_RED_HAT=13,
	M_KARATE=14,
	M_ARTIST=15,
	M_GARDENER_WITH_BUCKET=16,
	F_GARDENER_WITH_BUCKET=17,
	F_COWGIRL=18,
	M_BRO_BLUE_VISOR=19,
	M_DAD_WITH_KID=20,
	F_WOMAN_WITH_COCONUTS=21,
	F_GIRL_IN_PIKACHU_COSTUME=22,
	DUO_DANCING_COUPLE=23,
	M_ACE_TRAINER=24,
	F_ACE_TRAINER=25,
	F_WAITRESS=26,
	M_SAMURAI=27,
	M_BOY_NINJA=28,
	M_MAGICIAN=29,
	F_BIRD_CATCHER=30,
	DUO_ACE_TRAINERS=31,
	M_RICH_BOY=32,
	F_RICH_GIRL=33,
	M_RICH_OLD_MAN=34,
	F_RICH_OLD_WOMAN=35,
	F_BLONDIE=36,
	M_NERD_WITH_GLASSES=37,
	M_COP=38,
	M_RANGER=39,
	F_RANGER=40,
	M_SCIENTIST=41,
	M_SWIMMER=42,
	F_SWIMMER=43,
	M_SWIMMING_BOY=44,
	F_SWIMMING_GIRL=45,
	M_SAILOR=46,
	DUO_SWIMMERS=47,
	M_INDIANA_JONES=48,
	M_PSYCHIC=49,
	F_PSYCHIC=50,
	M_DETECTIVE=51,
	M_ROCKSTAR=52,
	M_SNOW_PATROL=53,
	F_SNOW_PATROL=54,
	M_SKIER=55,
	F_SKIER=56,
	M_BALD_GANG_DUDE=57,
	M_CLOWN=58,
	M_TECHNICIAN=59,
	M_BOY_NERD=60,
	F_GIRL_WITH_LUNCHBOX=61,
	M_BLONDE_HIPSTER=62,
	M_GREEN_HAIR_HIPSTER=63,
	F_SCIENTIST_WOMAN=64,
	M_REDHEAD=65,
	F_PURPLE_SUIT=66,
	F_BLACK_TRENCHCOAT_BLONDE_HAIR=67,
	DUO_FARMERS=68,
	M_FARMER=69,
	M_CONSTRUCTION=70,
	F_GREEN_SHAWL=71,
	F_PINK_HAIR_GIRL=72,
	M_CRASHER_WAKE=73,
	F_PURPLE_DRESS_AND_HAIR=74,
	M_DIGGER=75,
	F_ANGRY_SCHOOLGIRL_BLUE_SKIRT=76,
	M_FOURTH_HOKAGE_BLUE_JACKET=77,
	F_GIRL_WITH_PARASOL=78,
	M_WAITER=79,
	DUO_CAMERA_CREW=80,
	M_CAMERAMAN=81,
	F_NEWS_ANCHOR=82,
	F_HOSTESS=83,
	F_GALACTIC_REDHEAD=84,
	M_GALACTIC_GRAY_HAIR=85,
	F_GALACTIC_PINK_HAIR=86,
	M_GALACTIC_BLUE_HAIR=87,
	M_GALACTIC_THUG=88,
	F_GALACTIC_THUG=89,
	M_GREEN_TRENCHCOAT=90,
	F_HAYLEY=94;
		
	public static BufferedImage[] battleSprites = new BufferedImage[95];
	
	public static void initialize(){
		for(int i=0; i< battleSprites.length; i++){
			try {
				battleSprites[i] = ImageIO.read(Trainer.class.getResource("/PokemonFiles/TrainerImages/Battle/Battle"+i+".png"));
			} catch (IOException e) {
				battleSprites[i] = null;
				e.printStackTrace();
			}
		}
	}
	
}
